linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - goconst
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
